import "./globals.css";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import Providers from "./lib/Providers";
import Navbar from "@/components/shared/Navbar/Navbar";
export const metadata: Metadata = {
  title: "EWN Project",
  description: "Generated by Md Rifat",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <Providers>
            <Navbar/>
            <div className="min-h-screen pt-20">{children}</div>
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
